### ISSUE TITLE
Table creation fails

### ISSUE THREAD

**Issue by janhoeckesfeld** [MrNavaStar/InvSync#11]
The Mod does not create the table correctly. I had to add the following table to the database:

```
CREATE TABLE InvSyncPlayerData (
    ID text,
    STRINGS text,
    INTS text,
    FLOATS text,
    DOUBLES text,
    JSON text,
    NBT text
);
```

After this the SQLite Database worked, but the mysql version does not work:

```
[STDERR]: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'EXCLUSIVE' at line 1
[STDERR]:         at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[STDERR]:         at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[STDERR]:         at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:768)
[STDERR]:         at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:653)
[STDERR]:         at mrnavastar.sqlib.util.SqlManager.beginTransaction(SqlManager.java:50)
[STDERR]:         at mrnavastar.sqlib.api.Table.beginTransaction(Table.java:49)
[STDERR]:         at mrnavastar.sqlib.api.Table.addToDatabase(Table.java:28)
[STDERR]:         at mrnavastar.sqlib.api.databases.Database.add(Database.java:25)
[STDERR]:         at mrnavastar.sqlib.api.databases.Database.createTable(Database.java:32)
[STDERR]:         at mrnavastar.invsync.InvSync.onInitialize(InvSync.java:42)
```

Or after a player leaves:

```
[STDERR]: java.sql.SQLException: Illegal operation on empty result set.
[STDERR]:     at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
[STDERR]:     at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
[STDERR]:     at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
[STDERR]:     at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
[STDERR]:     at com.mysql.cj.jdbc.result.ResultSetImpl.checkRowPos(ResultSetImpl.java:517)
[STDERR]:     at com.mysql.cj.jdbc.result.ResultSetImpl.getString(ResultSetImpl.java:870)
[STDERR]:     at com.mysql.cj.jdbc.result.ResultSetImpl.getString(ResultSetImpl.java:888)
[STDERR]:     at mrnavastar.sqlib.util.SqlManager.readJson(SqlManager.java:128)
[STDERR]:     at mrnavastar.sqlib.api.DataContainer.putIntoDatabase(DataContainer.java:56)
[STDERR]:     at mrnavastar.sqlib.api.DataContainer.put(DataContainer.java:92)
[STDERR]:     at mrnavastar.invsync.util.Converter.savePlayerData(Converter.java:80)
[STDERR]:     at mrnavastar.invsync.InvSync.lambda$onInitialize$1(InvSync.java:60)
```

Is this caused by a newer Mysql version? This might belong into the sqlib repository.
Or is this only occuring on my end?

**Comment by MrNavaStar** [comment]
Interesting, yea this would be an issue with sqlib, but that's alright. Strange that this issue is only coming up now. I'll take a look at it later today.

**Comment by MrNavaStar** [comment]
Might be fixed in the newest release
