### ISSUE TITLE
SQLSyntaxErrorException

### ISSUE THREAD

**Issue by Khikki** [MrNavaStar/InvSync#12]
Actually the problem is when running the last compiled version v2.1 - 1.18.
Is it because I use MariaBD?
```
> [21:36:50] [main/INFO]: [InvSync] Initializing...
> [21:36:51] [ForkJoinPool.commonPool-worker-1/INFO]: Essential Commands is up to date!
> [21:36:51] [main/INFO]: [STDERR]: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'EXCLUSIVE' at line 1
> [21:36:51] [main/INFO]: [STDERR]:       at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
> [21:36:51] [main/INFO]: [STDERR]:       at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
> [21:36:51] [main/INFO]: [STDERR]:       at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:768)
> [21:36:51] [main/INFO]: [STDERR]:       at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:653)
> [21:36:51] [main/INFO]: [STDERR]:       at mrnavastar.sqlib.util.SqlManager.beginTransaction(SqlManager.java:50)
> [21:36:51] [main/INFO]: [STDERR]:       at mrnavastar.sqlib.api.Table.beginTransaction(Table.java:49)
> [21:36:51] [main/INFO]: [STDERR]:       at mrnavastar.sqlib.api.Table.addToDatabase(Table.java:28)
> [21:36:51] [main/INFO]: [STDERR]:       at mrnavastar.sqlib.api.databases.Database.add(Database.java:25)
> [21:36:51] [main/INFO]: [STDERR]:       at mrnavastar.sqlib.api.databases.Database.createTable(Database.java:32)
> [21:36:51] [main/INFO]: [STDERR]:       at mrnavastar.invsync.InvSync.onInitialize(InvSync.java:42)
> [21:36:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
> [21:36:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
> [21:36:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62)
> [21:36:51] [main/INFO]: [STDERR]:       at net.minecraft.server.Main.main(Main.java:102)
> [21:36:51] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [21:36:51] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> [21:36:51] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [21:36:51] [main/INFO]: [STDERR]:       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> [21:36:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
> [21:36:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
> [21:36:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
> [21:36:51] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [21:36:51] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> [21:36:51] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [21:36:51] [main/INFO]: [STDERR]:       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> [21:36:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66)
> [21:36:51] [main/INFO]: [STDERR]: java.sql.SQLSyntaxErrorException: BLOB/TEXT column 'ID' used in key specification without a key length
> [21:36:51] [main/INFO]: [STDERR]:       at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
> [21:36:51] [main/INFO]: [STDERR]:       at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
> [21:36:51] [main/INFO]: [STDERR]:       at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
> [21:36:51] [main/INFO]: [STDERR]:       at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1098)
> [21:36:51] [main/INFO]: [STDERR]:       at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1046)
> [21:36:51] [main/INFO]: [STDERR]:       at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1371)
> [21:36:51] [main/INFO]: [STDERR]:       at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1031)
> [21:36:51] [main/INFO]: [STDERR]:       at mrnavastar.sqlib.util.SqlManager.createTable(SqlManager.java:74)
> [21:36:51] [main/INFO]: [STDERR]:       at mrnavastar.sqlib.api.Table.addToDatabase(Table.java:29)
> [21:36:51] [main/INFO]: [STDERR]:       at mrnavastar.sqlib.api.databases.Database.add(Database.java:25)
> [21:36:51] [main/INFO]: [STDERR]:       at mrnavastar.sqlib.api.databases.Database.createTable(Database.java:32)
> [21:36:51] [main/INFO]: [STDERR]:       at mrnavastar.invsync.InvSync.onInitialize(InvSync.java:42)
> [21:36:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
> [21:36:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
> [21:36:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62)
> [21:36:51] [main/INFO]: [STDERR]:       at net.minecraft.server.Main.main(Main.java:102)
> [21:36:51] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [21:36:51] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> [21:36:51] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [21:36:51] [main/INFO]: [STDERR]:       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> [21:36:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
> [21:36:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
> [21:36:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
> [21:36:51] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [21:36:51] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> [21:36:51] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [21:36:51] [main/INFO]: [STDERR]:       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> [21:36:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66)
> [21:36:51] [main/INFO]: [STDERR]: java.sql.SQLSyntaxErrorException: Table 'Minecraft.PlayerData' doesn't exist
> [21:36:51] [main/INFO]: [STDERR]:       at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
> [21:36:51] [main/INFO]: [STDERR]:       at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
> [21:36:51] [main/INFO]: [STDERR]:       at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
> [21:36:51] [main/INFO]: [STDERR]:       at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009)
> [21:36:51] [main/INFO]: [STDERR]:       at mrnavastar.sqlib.util.SqlManager.listIds(SqlManager.java:110)
> [21:36:51] [main/INFO]: [STDERR]:       at mrnavastar.sqlib.api.Table.getIds(Table.java:66)
> [21:36:51] [main/INFO]: [STDERR]:       at mrnavastar.sqlib.api.Table.addToDatabase(Table.java:31)
> [21:36:51] [main/INFO]: [STDERR]:       at mrnavastar.sqlib.api.databases.Database.add(Database.java:25)
> [21:36:51] [main/INFO]: [STDERR]:       at mrnavastar.sqlib.api.databases.Database.createTable(Database.java:32)
> [21:36:51] [main/INFO]: [STDERR]:       at mrnavastar.invsync.InvSync.onInitialize(InvSync.java:42)
> [21:36:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
> [21:36:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
> [21:36:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62)
> [21:36:51] [main/INFO]: [STDERR]:       at net.minecraft.server.Main.main(Main.java:102)
> [21:36:51] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [21:36:51] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> [21:36:51] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [21:36:51] [main/INFO]: [STDERR]:       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> [21:36:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
> [21:36:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
> [21:36:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
> [21:36:51] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [21:36:51] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> [21:36:51] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [21:36:51] [main/INFO]: [STDERR]:       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> [21:36:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66)
> [21:36:51] [main/INFO]: [InvSync] Complete!
> 
```

**Comment by MrNavaStar** [comment]
I haven't pushed the official 1.18 release. There are some fixes that need to be applied to SQLib regarding mysql server. SQLite should work in the meantime.

**Comment by Khikki** [comment]
within what time should we wait for 1.18 release?

**Comment by MrNavaStar** [comment]
I'll work on it this weekend

**Comment by Khikki** [comment]
ty.
