### ISSUE TITLE
Crash on player join

### ISSUE THREAD

**Issue by sauramel** [MrNavaStar/InvSync#34]
This doesnt seem specific to any particular player but not sure what is causing this crash.
`[04:46:03] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.AssertionError: null
	at com.google.gson.internal.bind.JsonTreeReader.peek(JsonTreeReader.java:146) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:161) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.9.jar:?]
	at com.google.gson.TypeAdapter.fromJsonTree(TypeAdapter.java:285) ~[gson-2.8.9.jar:?]
	at net.minecraft.class_2985.INVSYNC$load(class_2985.java:3581) ~[server-intermediary.jar:?]
	at mrnavastar.invsync.util.Converter.updatePlayerData(Converter.java:55) ~[_added-invsync-v2.3.1.jar:?]
	at mrnavastar.invsync.InvSync.lambda$onInitialize$0(InvSync.java:64) ~[_added-invsync-v2.3.1.jar:?]
	at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$2(ServerPlayConnectionEvents.java:48) ~[fabric-networking-api-v1-1.1.0+442de8b8a9-4071c58cedb5d399.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.onClientReady(ServerPlayNetworkAddon.java:65) ~[fabric-networking-api-v1-1.1.0+442de8b8a9-4071c58cedb5d399.jar:?]
	at net.minecraft.class_3324.handler$cka000$handlePlayerConnection(class_3324.java:10492) ~[server-intermediary.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:197) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_33800(class_3248.java:140) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_14384(class_3248.java:127) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.redirect$ckb000$handlePlayerJoin(class_3248.java:563) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_18785(class_3248.java:77) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:242) ~[server-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:182) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by MrNavaStar** [comment]
Is this random or it happens every time? SQLite or mysql? Steps to reproduce? Any other information you can give me that would be great.

**Comment by MrNavaStar** [comment]
Okay If I can't get any more info than this I unfortunately can't do anything

**Comment by sauramel** [comment]
Using MySQL, doesn't happen every time and stopped happening after I reset
the DB
