### ISSUE TITLE
Issue with switching servers and InvSync

### ISSUE THREAD

**Issue by anthonydeaver** [MrNavaStar/InvSync#51]
Just hit a fatal issue when switching servers: (via /server <server>)
```
[18:54:05] [Netty Server IO #2/ERROR]: [SQLib] Failed to connect to database! Is there already a connection open?
[18:54:05] [Netty Server IO #2/INFO]: [STDERR]: java.sql.SQLNonTransientConnectionException: Too many connections
[18:54:05] [Netty Server IO #2/INFO]: [STDERR]:         at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
[18:54:05] [Netty Server IO #2/INFO]: [STDERR]:         at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[18:54:05] [Netty Server IO #2/INFO]: [STDERR]:         at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
[18:54:05] [Netty Server IO #2/INFO]: [STDERR]:         at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
[18:54:05] [Netty Server IO #2/INFO]: [STDERR]:         at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
[18:54:05] [Netty Server IO #2/INFO]: [STDERR]:         at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
[18:54:05] [Netty Server IO #2/INFO]: [STDERR]:         at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
[18:54:05] [Netty Server IO #2/INFO]: [STDERR]:         at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
[18:54:05] [Netty Server IO #2/INFO]: [STDERR]:         at mrnavastar.sqlib.util.SqlManager.connectMYSQL(SqlManager.java:29)
[18:54:05] [Netty Server IO #2/INFO]: [STDERR]:         at mrnavastar.sqlib.api.databases.MySQLDatabase.connect(MySQLDatabase.java:28)
[18:54:05] [Netty Server IO #2/INFO]: [STDERR]:         at mrnavastar.sqlib.api.Table.beginTransaction(Table.java:48)
[18:54:05] [Netty Server IO #2/INFO]: [STDERR]:         at mrnavastar.invsync.InvSync.lambda$onInitialize$1(InvSync.java:72)
[18:54:05] [Netty Server IO #2/INFO]: [STDERR]:         at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$4(ServerPlayConnectionEvents.java:59)
[18:54:05] [Netty Server IO #2/INFO]: [STDERR]:         at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.invokeDisconnectEvent(ServerPlayNetworkAddon.java:140)
[18:54:05] [Netty Server IO #2/INFO]: [STDERR]:         at net.fabricmc.fabric.impl.networking.AbstractNetworkAddon.handleDisconnect(AbstractNetworkAddon.java:131)
[18:54:05] [Netty Server IO #2/INFO]: [STDERR]:         at net.minecraft.class_2535.handler$zna000$handleDisconnect(class_2535.java:1593)
[18:54:05] [Netty Server IO #2/INFO]: [STDERR]:         at net.minecraft.class_2535.channelInactive(class_2535.java)
```
and not I can't even log into the Lobby

I have both server configured identically (copy pasted the file from one to the other)

MC version: 1.19.2
Fabric API:  fabric-api 0.62.0+1.19.2
 invsync v2.3.1
 Fabric 0.14.9
 
 Anything else that will help let me know.

**Comment by anthonydeaver** [comment]
I can't even connect to the DB because there are too many connections. Nothing except InvSync and LuckPerms uses this DB and I have had no issues until installing InvSync. Is it not terminating connections maybe?

**Comment by MrNavaStar** [comment]
Hmm that's strange, I'm not sure why that's happening. I've never tested the mod sharing a database with another mod. I know Invsync closes it's connection with the database, but it's possible luck perms does not. If it was Invsyncs fault I would expect luck perms to throw the too many connections error. 

For now I would just give Invsync its own database or set the [max connections](https://docs.rackspace.com/support/how-to/too-many-connections-error-in-mysql/) higher on your database. If you can find any information on how luck perms handles the database I would be happy to take a look.
