### ISSUE TITLE
Database connection closed on player disconnect

### ISSUE THREAD

**Issue by Raveh00** [MrNavaStar/InvSync#54]
When trying the mod on a fresh server, I have a `database connection closed` error message when a player disconnect.
It happens if the player connect and disconnect before the saveAll method is called.
I'm using SQLite, it correctly generates the database but it can't write the player infos in it.
After investigations, it seems to be caused by these lines in InvSync.java:
```
if (playerDataContainer == null) {
                playerDataContainer = playerData.createDataContainer(player.getUuid());
                playerData.put(playerDataContainer);
            }
```
When looking at the methods in Table class of SQLib, we can see that the call to `put` with the `playerDataContainer` will call `this.drop`. But in the `drop` method there is a call to `this.database.disconnect()`. So when we return in the `put` method, the call to `SqlManager.createRow` failed because the connection was disconnected in `drop`.
```
public DataContainer createDataContainer(String id) {
        DataContainer dataContainer = new DataContainer(id);
        this.put(dataContainer);
        return dataContainer;
    }

    public void put(DataContainer dataContainer) {
        if (!this.isInTransaction) this.database.connect();
        if (this.get(dataContainer.getId()) != null) this.drop(dataContainer);
        SqlManager.createRow(this.name, dataContainer.getId());
        this.dataContainers.add(dataContainer);
        dataContainer.link(this, this.database);
        if (!this.isInTransaction) this.database.disconnect();
    }

    public void drop(DataContainer dataContainer) {
        if (!this.isInTransaction) this.database.connect();
        SqlManager.deleteRow(this.getName(), dataContainer.getId());
        dataContainer.link(null, null);
        this.dataContainers.remove(dataContainer);
        if (!this.isInTransaction) this.database.disconnect();
    }
```
The call to `playerData.put(playerDataContainer);` doesn't seems necessary since it's already done in the `createDataContainer` method.
But maybe it's something which should be fixed in the SQLite library.
Don't know exactly :)

Here is the full log of the server when it fails
```
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[16:41:06] [main/INFO]: Loading Minecraft 1.19.3 with Fabric Loader 0.14.12
[16:41:06] [ForkJoinPool-1-worker-3/WARN]: Mod invsync uses the version v2.3.2 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'v2'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[16:41:07] [main/INFO]: Loading 46 mods:
	- fabric-api 0.72.0+1.19.3
	- fabric-api-base 0.4.20+afca2f3e85 via fabric-api
	- fabric-api-lookup-api-v1 1.6.19+49abcf7e85 via fabric-api
	- fabric-biome-api-v1 12.1.0+b5d379b085 via fabric-api
	- fabric-block-api-v1 1.0.4+e022e5d185 via fabric-api
	- fabric-command-api-v1 1.2.21+f71b366f85 via fabric-api
	- fabric-command-api-v2 2.2.0+3fc4752e85 via fabric-api
	- fabric-commands-v0 0.2.38+df3654b385 via fabric-api
	- fabric-containers-v0 0.1.46+df3654b385 via fabric-api
	- fabric-content-registries-v0 3.5.0+1d37d50285 via fabric-api
	- fabric-convention-tags-v1 1.2.1+8e4e694f85 via fabric-api
	- fabric-crash-report-info-v1 0.2.13+aeb40ebe85 via fabric-api
	- fabric-data-generation-api-v1 11.1.4+1134c5b885 via fabric-api
	- fabric-dimensions-v1 2.1.40+48349a3f85 via fabric-api
	- fabric-entity-events-v1 1.5.6+b83334a085 via fabric-api
	- fabric-events-interaction-v0 0.4.39+3baeb27a85 via fabric-api
	- fabric-events-lifecycle-v0 0.2.42+df3654b385 via fabric-api
	- fabric-game-rule-api-v1 1.0.29+99f9db8085 via fabric-api
	- fabric-item-api-v1 2.1.8+1134c5b885 via fabric-api
	- fabric-item-group-api-v1 2.1.11+1134c5b885 via fabric-api
	- fabric-lifecycle-events-v1 2.2.9+23a79c8a85 via fabric-api
	- fabric-loot-api-v2 1.1.19+75e9821185 via fabric-api
	- fabric-loot-tables-v1 1.1.23+9e7660c685 via fabric-api
	- fabric-message-api-v1 5.0.13+6ede1da985 via fabric-api
	- fabric-mining-level-api-v1 2.1.30+49abcf7e85 via fabric-api
	- fabric-networking-api-v1 1.2.16+4017a8cb85 via fabric-api
	- fabric-networking-v0 0.3.33+df3654b385 via fabric-api
	- fabric-object-builder-api-v1 5.3.0+85f102ee85 via fabric-api
	- fabric-particles-v1 1.0.19+f1e4495b85 via fabric-api
	- fabric-recipe-api-v1 1.0.0+5176f73d85 via fabric-api
	- fabric-registry-sync-v0 2.0.4+1134c5b885 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.24+afca2f3e85 via fabric-api
	- fabric-rendering-fluids-v1 3.0.17+f1e4495b85 via fabric-api
	- fabric-resource-conditions-api-v1 2.2.2+1134c5b885 via fabric-api
	- fabric-resource-loader-v0 0.10.4+a91e48b785 via fabric-api
	- fabric-screen-handler-api-v1 1.3.12+99f9db8085 via fabric-api
	- fabric-transfer-api-v1 2.1.14+ccd377ba85 via fabric-api
	- fabric-transitive-access-wideners-v1 2.3.0+5b9a588b85 via fabric-api
	- fabricloader 0.14.12
	- invsync v2.3.2
	- java 17
	- microconfig 2.2.1 via invsync
	- minecraft 1.19.3
	- mysql_mysql-connector-java 8.0.30 via sqlib
	- org_xerial_sqlite-jdbc 3.36.0.3 via sqlib
	- sqlib 1.3.2 via invsync
[16:41:07] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/raveh/Minecraft%20Servers/Fabric%20Test/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[16:41:07] [main/INFO]: Compatibility level set to JAVA_16
[16:41:07] [main/INFO]: Compatibility level set to JAVA_17
[16:41:13] [main/INFO]: Building unoptimized datafixer
[16:41:15] [main/INFO]: [InvSync] Initializing...
[16:41:15] [main/INFO]: [InvSync] Database initialized successfully!
[16:41:15] [main/INFO]: [InvSync] Complete!
[16:41:15] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[16:41:16] [main/INFO]: Found new data pack fabric, loading it automatically
[16:41:18] [main/INFO]: Loaded 7 recipes
[16:41:18] [main/INFO]: Loaded 1179 advancements
[16:41:19] [main/INFO]: Applied 0 biome modifications to 0 of 63 new biomes in 4.531 ms
[16:41:19] [Server thread/INFO]: Starting minecraft server version 1.19.3
[16:41:19] [Server thread/INFO]: Loading properties
[16:41:19] [Server thread/INFO]: Default game type: SURVIVAL
[16:41:19] [Server thread/INFO]: Generating keypair
[16:41:19] [Server thread/INFO]: Starting Minecraft server on *:30067
[16:41:19] [Server thread/INFO]: Using epoll channel type
[16:41:19] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[16:41:19] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[16:41:19] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[16:41:19] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[16:41:19] [Server thread/INFO]: Preparing level "world"
[16:41:26] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[16:41:28] [Worker-Main-3/INFO]: Preparing spawn area: 0%
[16:41:28] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[16:41:28] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[16:41:28] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[16:41:28] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[16:41:29] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[16:41:29] [Worker-Main-3/INFO]: Preparing spawn area: 0%
[16:41:30] [Worker-Main-3/INFO]: Preparing spawn area: 1%
[16:41:30] [Worker-Main-2/INFO]: Preparing spawn area: 2%
[16:41:31] [Worker-Main-3/INFO]: Preparing spawn area: 3%
[16:41:31] [Worker-Main-2/INFO]: Preparing spawn area: 4%
[16:41:32] [Worker-Main-1/INFO]: Preparing spawn area: 5%
[16:41:32] [Worker-Main-2/INFO]: Preparing spawn area: 6%
[16:41:33] [Worker-Main-1/INFO]: Preparing spawn area: 6%
[16:41:33] [Worker-Main-1/INFO]: Preparing spawn area: 8%
[16:41:34] [Worker-Main-3/INFO]: Preparing spawn area: 9%
[16:41:34] [Worker-Main-3/INFO]: Preparing spawn area: 10%
[16:41:35] [Worker-Main-2/INFO]: Preparing spawn area: 11%
[16:41:35] [Worker-Main-3/INFO]: Preparing spawn area: 13%
[16:41:36] [Worker-Main-1/INFO]: Preparing spawn area: 15%
[16:41:36] [Worker-Main-1/INFO]: Preparing spawn area: 16%
[16:41:37] [Worker-Main-3/INFO]: Preparing spawn area: 17%
[16:41:37] [Worker-Main-1/INFO]: Preparing spawn area: 20%
[16:41:38] [Worker-Main-1/INFO]: Preparing spawn area: 22%
[16:41:38] [Worker-Main-3/INFO]: Preparing spawn area: 23%
[16:41:39] [Worker-Main-3/INFO]: Preparing spawn area: 25%
[16:41:39] [Worker-Main-1/INFO]: Preparing spawn area: 26%
[16:41:40] [Worker-Main-3/INFO]: Preparing spawn area: 28%
[16:41:40] [Worker-Main-1/INFO]: Preparing spawn area: 31%
[16:41:41] [Worker-Main-2/INFO]: Preparing spawn area: 32%
[16:41:41] [Worker-Main-3/INFO]: Preparing spawn area: 34%
[16:41:44] [Worker-Main-1/INFO]: Preparing spawn area: 35%
[16:41:44] [Worker-Main-1/INFO]: Preparing spawn area: 35%
[16:41:44] [Worker-Main-1/INFO]: Preparing spawn area: 35%
[16:41:44] [Worker-Main-1/INFO]: Preparing spawn area: 35%
[16:41:44] [Worker-Main-1/INFO]: Preparing spawn area: 36%
[16:41:44] [Worker-Main-1/INFO]: Preparing spawn area: 38%
[16:41:45] [Worker-Main-2/INFO]: Preparing spawn area: 40%
[16:41:45] [Worker-Main-3/INFO]: Preparing spawn area: 42%
[16:41:46] [Worker-Main-3/INFO]: Preparing spawn area: 44%
[16:41:46] [Worker-Main-3/INFO]: Preparing spawn area: 46%
[16:41:47] [Worker-Main-2/INFO]: Preparing spawn area: 49%
[16:41:47] [Worker-Main-2/INFO]: Preparing spawn area: 51%
[16:41:48] [Worker-Main-1/INFO]: Preparing spawn area: 54%
[16:41:48] [Worker-Main-2/INFO]: Preparing spawn area: 55%
[16:41:49] [Worker-Main-2/INFO]: Preparing spawn area: 56%
[16:41:49] [Worker-Main-3/INFO]: Preparing spawn area: 58%
[16:41:50] [Worker-Main-3/INFO]: Preparing spawn area: 61%
[16:41:50] [Worker-Main-2/INFO]: Preparing spawn area: 63%
[16:41:51] [Worker-Main-2/INFO]: Preparing spawn area: 66%
[16:41:51] [Worker-Main-1/INFO]: Preparing spawn area: 68%
[16:41:52] [Worker-Main-1/INFO]: Preparing spawn area: 70%
[16:41:52] [Worker-Main-1/INFO]: Preparing spawn area: 72%
[16:41:53] [Worker-Main-2/INFO]: Preparing spawn area: 75%
[16:41:53] [Worker-Main-1/INFO]: Preparing spawn area: 77%
[16:41:54] [Worker-Main-2/INFO]: Preparing spawn area: 80%
[16:41:54] [Worker-Main-1/INFO]: Preparing spawn area: 83%
[16:41:55] [Worker-Main-3/INFO]: Preparing spawn area: 84%
[16:41:55] [Worker-Main-2/INFO]: Preparing spawn area: 86%
[16:41:56] [Worker-Main-3/INFO]: Preparing spawn area: 88%
[16:41:56] [Worker-Main-2/INFO]: Preparing spawn area: 91%
[16:41:57] [Worker-Main-2/INFO]: Preparing spawn area: 94%
[16:41:57] [Worker-Main-2/INFO]: Preparing spawn area: 97%
[16:41:58] [Server thread/INFO]: Time elapsed: 31447 ms
[16:41:58] [Server thread/INFO]: Done (38.828s)! For help, type "help"
[16:42:02] [Server thread/INFO]: XXXXXX[/127.0.0.1:37534] logged in with entity id 189 at (6.5, 78.0, -20.5)
[16:42:02] [Server thread/INFO]: XXXXXX joined the game
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: java.sql.SQLException: database connection closed
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at org.sqlite.SQLiteConnection.checkOpen(SQLiteConnection.java:399)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:32)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at mrnavastar.sqlib.util.SqlManager.createRow(SqlManager.java:97)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at mrnavastar.sqlib.api.Table.put(Table.java:100)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at mrnavastar.invsync.InvSync.lambda$onInitialize$3(InvSync.java:78)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$4(ServerPlayConnectionEvents.java:59)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.invokeDisconnectEvent(ServerPlayNetworkAddon.java:140)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at net.fabricmc.fabric.impl.networking.AbstractNetworkAddon.handleDisconnect(AbstractNetworkAddon.java:131)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at net.minecraft.class_2535.handler$zdi000$handleDisconnect(class_2535.java:593)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at net.minecraft.class_2535.channelInactive(class_2535.java)
[16:42:09] [Server thread/INFO]: XXXXXX lost connection: Disconnected
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[16:42:09] [Server thread/INFO]: XXXXXX left the game
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:401)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:366)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:401)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:366)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:401)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:366)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: java.sql.SQLException: ResultSet closed
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at org.sqlite.core.CoreResultSet.checkOpen(CoreResultSet.java:76)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:39)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at org.sqlite.jdbc3.JDBC3ResultSet.getString(JDBC3ResultSet.java:446)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at mrnavastar.sqlib.util.SqlManager.readJson(SqlManager.java:143)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at mrnavastar.sqlib.api.DataContainer.getFromDatabase(DataContainer.java:76)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at mrnavastar.sqlib.api.DataContainer.put(DataContainer.java:120)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at mrnavastar.invsync.services.CoreSyncProcedures.lambda$init$1(CoreSyncProcedures.java:21)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at mrnavastar.invsync.api.ServerSyncEvents.lambda$static$2(ServerSyncEvents.java:20)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at mrnavastar.invsync.InvSync.lambda$onInitialize$3(InvSync.java:82)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$4(ServerPlayConnectionEvents.java:59)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.invokeDisconnectEvent(ServerPlayNetworkAddon.java:140)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at net.fabricmc.fabric.impl.networking.AbstractNetworkAddon.handleDisconnect(AbstractNetworkAddon.java:131)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at net.minecraft.class_2535.handler$zdi000$handleDisconnect(class_2535.java:593)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at net.minecraft.class_2535.channelInactive(class_2535.java)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:401)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:366)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:401)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:366)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:401)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:366)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[16:42:09] [Netty Epoll Server IO #2/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by MrNavaStar** [comment]
Good catch! I have been facing some odd sql errors lately, but I have been having difficulty tracking it down. I'll definitely look into fixing this right away. I think you are right about the put function call being unnecessary. I believe the extra put call is left over from an older version of sqlib, but I'm not sure.

**Comment by MrNavaStar** [comment]
@Raveh00 Would you be able to test this new [build](https://drive.google.com/file/d/1B92b2MiDfknP3En6rZApLQHnGole3o9U/view?usp=share_link) for me?

**Comment by Raveh00** [comment]
This is fixed with your new build.
Thank you!

**Comment by MrNavaStar** [comment]
Awesome! I will create a release soon! Thanks so much!
