### ISSUE TITLE
Sync Advancement Crashes

### ISSUE THREAD

**Issue by AbrasiveBoar902** [MrNavaStar/InvSync#57]
Maybe because `writeAdvancementData` modifies `advancementToProgress`(or other `LinkedHashMap`s) while `PlayerAdvancementTracker/sendUpdate` is reading it with iterator.

Caused
```
Description: Ticking entity

java.util.ConcurrentModificationException
at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:756)
at java.base/java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:778)
at net.minecraft.class_2985.method_12876(class_2985.java:285)
at net.minecraft.class_3222.method_5773(class_3222.java:428)
at net.minecraft.class_3218.method_18762(class_3218.java:621)
at net.minecraft.class_1937.method_18472(class_1937.java:561)
at net.minecraft.class_3218.method_18765(class_3218.java:411)
at net.minecraft.server.MinecraftServer.redirect$zkm000$ficUpdateSuppressionCrashTick(MinecraftServer.java:3711)
at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
at net.minecraft.class_3176.method_3813(class_3176.java:312)
at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
at net.minecraft.server.MinecraftServer.handler$zbc000$modifiedRunLoop(MinecraftServer.java:2810)
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:651)
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by MrNavaStar** [comment]
Oh pain, I'm surprised this has never come up. I'll look into fixing this hopefully this weekend.

**Comment by MrNavaStar** [comment]
Do you have any more logs you can share with me? Or any steps to reproduce the error?
