### ISSUE TITLE
SQLite ERROR player data not sync

### ISSUE THREAD

**Issue by AmibeSkyfy16** [MrNavaStar/InvSync#7]
[16:36:51] [Server thread/INFO]: [STDERR]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: PlayerData)
[16:36:51] [Server thread/INFO]: [STDERR]:      at org.sqlite.core.DB.newSQLException(DB.java:1012)
[16:36:51] [Server thread/INFO]: [STDERR]:      at org.sqlite.core.DB.newSQLException(DB.java:1024)
[16:36:51] [Server thread/INFO]: [STDERR]:      at org.sqlite.core.DB.throwex(DB.java:989)
[16:36:51] [Server thread/INFO]: [STDERR]:      at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
[16:36:51] [Server thread/INFO]: [STDERR]:      at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
[16:36:51] [Server thread/INFO]: [STDERR]:      at org.sqlite.core.DB.prepare(DB.java:257)
[16:36:51] [Server thread/INFO]: [STDERR]:      at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:66)
[16:36:51] [Server thread/INFO]: [STDERR]:      at com.mrnavastar.invsync.sql.SQLHandler.executeStatementAndReturn(SQLHandler.java:58)
[16:36:51] [Server thread/INFO]: [STDERR]:      at com.mrnavastar.invsync.sql.SQLHandler.loadString(SQLHandler.java:94)
[16:36:51] [Server thread/INFO]: [STDERR]:      at com.mrnavastar.invsync.sql.Table.get(Table.java:67)
[16:36:51] [Server thread/INFO]: [STDERR]:      at com.mrnavastar.invsync.conversion.PlayerDataConversion.sqlToNbt(PlayerDataConversion.java:111)
[16:36:51] [Server thread/INFO]: [STDERR]:      at com.mrnavastar.invsync.setup.PlayerDataSetup.lambda$start$0(PlayerDataSetup.java:20)
[16:36:51] [Server thread/INFO]: [STDERR]:      at com.mrnavastar.invsync.api.event.PlayerJoinCallback.lambda$static$0(PlayerJoinCallback.java:12)
[16:36:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3324.handler$zie000$onPlayerJoin(class_3324.java:2422)
[16:36:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3324.method_14570(class_3324.java:273)
[16:36:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3248.method_33800(class_3248.java:129)
[16:36:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3248.method_14384(class_3248.java:117)
[16:36:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3248.handler$zgi000$overwriteAcceptPlayer(class_3248.java:554)
[16:36:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3248.method_18785(class_3248.java:67)
[16:36:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_2535.method_10754(class_2535.java:234)
[16:36:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3242.method_14357(class_3242.java:183)
[16:36:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:904)
[16:36:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3176.method_3813(class_3176.java:334)
[16:36:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:833)
[16:36:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:692)
[16:36:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274)
[16:36:51] [Server thread/INFO]: [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:831)
[16:36:51] [Server thread/INFO]: [STDERR]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: PlayerData)
[16:36:51] [Server thread/INFO]: [STDERR]:      at org.sqlite.core.DB.newSQLException(DB.java:1012)
[16:36:51] [Server thread/INFO]: [STDERR]:      at org.sqlite.core.DB.newSQLException(DB.java:1024)
[16:36:51] [Server thread/INFO]: [STDERR]:      at org.sqlite.core.DB.throwex(DB.java:989)
[16:36:51] [Server thread/INFO]: [STDERR]:      at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
[16:36:51] [Server thread/INFO]: [STDERR]:      at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
[16:36:51] [Server thread/INFO]: [STDERR]:      at org.sqlite.core.DB.prepare(DB.java:257)
[16:36:51] [Server thread/INFO]: [STDERR]:      at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:66)
[16:36:51] [Server thread/INFO]: [STDERR]:      at com.mrnavastar.invsync.sql.SQLHandler.executeStatementAndReturn(SQLHandler.java:58)
[16:36:51] [Server thread/INFO]: [STDERR]:      at com.mrnavastar.invsync.sql.SQLHandler.loadString(SQLHandler.java:94)
[16:36:51] [Server thread/INFO]: [STDERR]:      at com.mrnavastar.invsync.sql.Table.get(Table.java:67)
[16:36:51] [Server thread/INFO]: [STDERR]:      at com.mrnavastar.invsync.conversion.PlayerDataConversion.sqlToNbt(PlayerDataConversion.java:116)
[16:36:51] [Server thread/INFO]: [STDERR]:      at com.mrnavastar.invsync.setup.PlayerDataSetup.lambda$start$0(PlayerDataSetup.java:20)
[16:36:51] [Server thread/INFO]: [STDERR]:      at com.mrnavastar.invsync.api.event.PlayerJoinCallback.lambda$static$0(PlayerJoinCallback.java:12)
[16:36:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3324.handler$zie000$onPlayerJoin(class_3324.java:2422)
[16:36:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3324.method_14570(class_3324.java:273)
[16:36:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3248.method_33800(class_3248.java:129)
[16:36:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3248.method_14384(class_3248.java:117)
[16:36:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3248.handler$zgi000$overwriteAcceptPlayer(class_3248.java:554)
[16:36:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3248.method_18785(class_3248.java:67)
[16:36:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_2535.method_10754(class_2535.java:234)
[16:36:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3242.method_14357(class_3242.java:183)
[16:36:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:904)
[16:36:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.class_3176.method_3813(class_3176.java:334)
[16:36:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:833)
[16:36:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:692)
[16:36:51] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274)
[16:36:51] [Server thread/INFO]: [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:831)
[16:36:51] [Server thread/INFO]: [invsync] Getting Player Data From database

**Comment by AmibeSkyfy16** [comment]
dont why but now its working
